# Generated by Django 2.2.8 on 2021-01-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
