# Generated by Django 2.2.8 on 2021-01-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci', '0002_firstmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
