# Generated by Django 2.2.8 on 2021-01-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci', '0003_auto_20210108_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
