# Generated by Django 3.1.5 on 2021-03-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci', '0004_auto_20210108_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstModel',
            new_name='DatasetModel',
        ),
    ]
