# Generated by Django 3.1.5 on 2021-03-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci', '0005_auto_20210325_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatasetModel',
            new_name='Dataset',
        ),
    ]
