# Generated by Django 3.1.5 on 2021-03-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci', '0006_auto_20210326_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
