# Generated by Django 3.1.5 on 2021-03-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci', '0007_auto_20210327_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
